### ISSUE TITLE
User reports that delete-then-download strategy isn't deleting the images beforehand.

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-supervisor#1233] opened 2020-03-30 12:18 UTC
Steps to reproduce:
* Set app's `RESIN_SUPERVISOR_UPDATE_STRATEGY` to `delete-then-download`
* Pinning the device to a different release

Expected results:
* images & containers getting deleted
* then the new download starts

Observed results:
* `balena ps -a` shows the containers being deleted
* dowload starts
* `balena images` still shows the old images
* download finishes
* the images of the old release get deleted

Supervisor logs:
```
Downloaded image 'registry2.balena-cloud.com/v2/faabd6c2ee0f68eef24f2a96b0eff77e@sha256:7d42ad0a910adaa67c2b4a47b6042927aa8758c0f1c680f2e640eab346f9d4c2'
Downloaded image 'registry2.balena-cloud.com/v2/f058387cf0cff9c098faab6e547932d0@sha256:e50314ff8c5b587753e47e365cd76c5efd33a462155f39b25775df03140a9bf9'
Deleting image 'registry2.balena-cloud.com/v2/f9c4be01fa5b8bb34b23270f19e97dbb@sha256:adad5135f662107ef25e8286c06b2bd6a5e7a689189befed38941538a1d74ad6'
Deleting image 'registry2.balena-cloud.com/v2/aac894f3f1b98f121fb53166bb4c9c7f@sha256:44fceb7229fca7c01b6a896b7875345797f5b626f0d55b702defee1ddcd708ec'
Deleted image 'registry2.balena-cloud.com/v2/f9c4be01fa5b8bb34b23270f19e97dbb@sha256:adad5135f662107ef25e8286c06b2bd6a5e7a689189befed38941538a1d74ad6'
Deleted image 'registry2.balena-cloud.com/v2/aac894f3f1b98f121fb53166bb4c9c7f@sha256:44fceb7229fca7c01b6a896b7875345797f5b626f0d55b702defee1ddcd708ec'
Installing service 'data sha256:c70ec64ff11be1e6d2180936396cd6935469811869c992c9f4997b1d1e6c8f84'
Installed service 'data sha256:c70ec64ff11be1e6d2180936396cd6935469811869c992c9f4997b1d1e6c8f84'
Starting service 'data sha256:c70ec64ff11be1e6d2180936396cd6935469811869c992c9f4997b1d1e6c8f84'
Started service 'data sha256:c70ec64ff11be1e6d2180936396cd6935469811869c992c9f4997b1d1e6c8f84'
Installing service 'proxy sha256:90b608566a4906414fc0d082e795915f6301e126d912271987034480888e2461'
Installed service 'proxy sha256:90b608566a4906414fc0d082e795915f6301e126d912271987034480888e2461'
Starting service 'proxy sha256:90b608566a4906414fc0d082e795915f6301e126d912271987034480888e2461'
Started service 'proxy sha256:90b608566a4906414fc0d082e795915f6301e126d912271987034480888e2461'
```

I also tried disabling deltas, just in case it was related, but I still observed the same behavior.

Device type: Nvidia Jetson Nano
balenaOS: 2.45.1+rev3
Supervisor: 10.3.7

**Comment by klutchell** [comment] 2021-06-30 17:41
I reproduced this issue with `12.8.8`

**Comment by 20k-ultra** [comment] 2021-06-30 17:44
thanks @klutchell, appreciate knowing it still exists. 

If there were any doubts if this is the intended - https://www.balena.io/docs/learn/deploy/release-strategy/update-strategies/#delete-then-download describes what should happen and the images are suppose to be deleted before downloading the next ones. I thought well what if the delete part only referred to the container then the policy is doing the right thing but that's not the case :p

**Comment by 20k-ultra** [comment] 2021-07-27 21:38
reminder to add test coverage to https://github.com/balena-os/balena-supervisor/blob/master/test/src/compose/application-manager.spec.ts for this update strategy

**Comment by 20k-ultra** [comment] 2021-07-28 04:51
Looks like the `delete-then-download` strategy is the exact same as `kill-then-download`

https://github.com/balena-os/balena-supervisor/blob/06c3f488e5703c37b110ed5554ff06c9506332fc/src/compose/update-strategies.ts#L33-L35

**Comment by cywang117** [comment] 2021-07-28 13:24
@20k-ultra I guess the thought behind implementing it in that way is that by default, a kill step removes the container, and the Supervisor will clean up any unused images. But maybe it wasn't considered *when* the Supervisor would clean up these images. In this case the Supervisor needs to remove images before downloading, so this definitely looks like an oversight

**Comment by pipex** [comment] 2021-08-20 14:43
The problem is in [this code](https://github.com/balena-os/balena-supervisor/blob/master/src/compose/application-manager.ts#L749-L761)

```
const potentialDeleteThenDownload = _(current)
        .flatMap((app) => _.values(app.services))
        .filter(
            (svc) =>
                svc.config.labels['io.balena.update.strategy'] ===
                    'delete-then-download' && svc.status === 'Stopped',
        )
        .value();

const imagesToRemove = _.filter(
    availableAndUnused.concat(potentialDeleteThenDownload.map(imageForService)),
    (image) => {
        const notUsedForDelta = !_.includes(deltaSources, image.name);
        const notUsedByProxyvisor = !_.some(proxyvisorImages, (proxyvisorImage) =>
            imageManager.isSameImage(image, {
                name: proxyvisorImage,
            }),
        );
        return notUsedForDelta && notUsedByProxyvisor;
    },
);
```

`imagesToRemove` is supposed to include images that are marked as `delete-then-download`, but not if they are `deltaSources`, however all images are delta sources so they are never removed. 

I think the solution is two fold
- Filter `delete-then-download` images out of `deltaSources`, an image is either a delta source or a image to be deleted, it cannot be both
- Get the `delete-then-download` label from the `target`, right now it's picking it from `current` which means if you add/remove the label to a newer release you won't see the behavior until the next release.

**Closed** 2021-11-16 20:04 UTC
Labels: type/bug
