### ISSUE TITLE
`PATCH /v1/device/host-config` should check for the hostname before changing it

### ISSUE THREAD

**Issue by lmbarros** [balena-os/balena-supervisor#2160] opened 2023-04-17 21:10 UTC
We had a user on support that apparently was unconditionally using the Supervisor API ([`PATCH /v1/device/host-config`](https://docs.balena.io/reference/supervisor/supervisor-api/#patch-v1devicehost-config)) to change the hostname right when their service starts. This causes the device to get into a loop (rename host, restart Engine, restart service, rename host...). This can be fixed by first using the GET endpoint to check if the hostname isn't already what they want.

But the Supervisor itself could do this check and become a no-op if the requested hostname is already the used one.

**Comment by pipex** [comment] 2023-04-18 18:48
Below is the logic that handles this. In a newer OS, the supervisor will never enter the `if` clause to restart the service. 

https://github.com/balena-os/balena-supervisor/blob/master/src/host-config.ts#L188-L203

This means the write will only happen if `config.set` is changing the value from what the supervisor knows (here is the logic of configJson handling). 
 
https://github.com/balena-os/balena-supervisor/blob/935a4fba59c82df916311cafe28b9a04da922809/src/config/configJson.ts#L58-L60

There is something else happening in the attached ticket that is not related to not checking. Somehow the hostname is not being reflected inside the containers.

**Comment by pipex** [comment] 2023-04-18 20:51
The OS removed `config-json.target` in v2.91.0 in favor of `config-json.service`, which means the supervisor is reverting to calling `balena-hostname`, which most likely is the cause of the issue. We are trying to figure out what is the best approach here

**Comment by pipex** [comment] 2023-07-19 21:39
This issue has been fixed in #2162 by removing the call to the balena-hostname service

**Closed by pipex** 2023-07-19 21:39 UTC
