### ISSUE TITLE
Device does not restart when config variables are applied

### ISSUE THREAD

**Issue by rahul-thakoor** [balena-os/balena-supervisor#1871] opened 2022-01-21 13:35 UTC
When a device joins a fleet where there are fleet level configuration variables set, Supervisor reports success when applying configs with `Applied boot config: {}`. however the device is not rebooted. This became apparent in [balena-rpiplay](https://hub.balena.io/gh_rahul_thakoor/balena-rpiplay) openFleet where uses report that the app is not working as intended. Upon investigating I noticed that the app is crashlooping. This is because it requires `gpu_mem` to be > 64MB but given that the config is changed but the device was not rebooted, the actual config was not loaded. 

`vcgencmd get_mem gpu` report the default 16MB
![image](https://user-images.githubusercontent.com/13220877/150535961-c6bc2b50-fe06-475b-a496-8ea29f5f3cc9.png)

`cat /mnt/boot/config.txt` showing `gpu_mem=256`
![image](https://user-images.githubusercontent.com/13220877/150536007-681828ff-9112-4ad7-9e58-0eee524ef8fd.png)

I was able to reproduce this on newer balenaOS versions on Pi4 with `2.88.5+rev1-v12.11.0`

BalenaOS `v2.75.0+rev1-v12.5.10` works fine.

## How to reproduce

- Create an fleet
- Add fleet level configurations
- Add a device to the fleet

## What is expected

Device should reboot once configs are applied

![image (10)](https://user-images.githubusercontent.com/13220877/150536798-c21f42ab-9eab-4d77-8cfc-823ce6515028.png)

## What is actual behaviour?

Device does not reboot.

FD thread: https://www.flowdock.com/app/rulemotion/balenalabs/threads/8X9OB8ehKewAXMolB6NUJv7e8q5

**Comment by pipex** [comment] 2022-01-25 14:02
Update on this. This only happens during provisioning, the supervisor applies the target state but it gets interrupted by the config-json service before getting a chance to reboot. 

After provisioning any change to config vars does trigger a reboot when required

**Comment by cywang117** [comment] 2022-01-27 21:35
Caused by https://github.com/balena-os/balena-supervisor/issues/1875

**Comment by pipex** [comment] 2022-03-18 13:32
Fixed in #1883

**Closed by pipex** 2022-03-18 13:32 UTC
Labels: High priority
