### ISSUE TITLE
After deconfiguring and reconfiguring, the supervisor attempts to pull an image with the incorrect key

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#676] opened 2018-06-11 10:22 UTC
Only happens when the `apiBackend` is the same.

**Comment by cywang117** [comment] 2022-12-19 21:14
Closing due to age. I've also not seen this behavior when re-provisioning a device in-place to the backend. If you do see this issue again, please reopen with Supervisor & OS versions, reproduction docker-compose, and logs.

**Closed by cywang117** 2022-12-19 21:14 UTC
Labels: type/bug, High priority, Needs more investigation
