### ISSUE TITLE
Downloading delta when source image is not on device

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1631] opened 2021-03-22 19:24 UTC
note: This is a suspicion!

As noted in https://github.com/balena-io/balena-supervisor/issues/1295 we have documented that if a delta begins to download on a device and the source image is not present then a 404 will be thrown by the daemon. This will look something like:

```
22.03.21 17:45:08 (+0100) Downloading delta for image 'registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e@sha256:10ff3d53b7618dae981ee40a75787f29d30e463220a6027b2cb927232cb2532c'
22.03.21 17:45:08 (+0100) Downloading delta for image 'registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad@sha256:8c235bbf206879513ba486afdfc9573e5d65cfde715fb430f0db6abcd8067949'
22.03.21 17:45:08 (+0100) Downloading delta for image 'registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1@sha256:38bd4832bbb77ef732cae0a580e58595f974b2e302be35acaf90e51fe44f0b62'
22.03.21 17:45:10 (+0100) Failed to download image 'registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad@sha256:8c235bbf206879513ba486afdfc9573e5d65cfde715fb430f0db6abcd8067949' due to '(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3: No such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3 '
22.03.21 17:45:10 (+0100) Failed to download image 'registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1@sha256:38bd4832bbb77ef732cae0a580e58595f974b2e302be35acaf90e51fe44f0b62' due to '(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505: No such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505 '
22.03.21 17:45:11 (+0100) Failed to download image 'registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e@sha256:10ff3d53b7618dae981ee40a75787f29d30e463220a6027b2cb927232cb2532c' due to '(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd: No such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd '
```

My suspicion is that because this device had preloaded applications then maybe if the Supervisor tries to apply the delta for a different release or image entirely then will it throw this 404 ?

For example, provision a device and preload Application 1. Then, push some new services (do not re-use previous services) and boot up device. The idea is that the Supervisor will now try to download delta's for a release it has no images (source) for. If this doesn't trigger the 404 then preload with Application 2 and then change the API so this device should be running Application 1 or something like that.

edit: reading the comments from the user which reported this issue they actually said they moved their device to another application! that helps with this theory.

**Comment by 20k-ultra** [comment] 2021-03-22 20:15
After performing the following steps the device reported 404 deltas:

    Preload application A to your SD card
    Boot device and everything works (application runs, device shows up on dashboard)
    Move device to application B
    Supervisor tries to pull application B images but shows the 404 delta error.

The device was successfully pulling 1 of the services but returned 404 for the rest. I think that one service may have been on Application A.

**Comment by 20k-ultra** [comment] 2021-03-22 20:54
cc @dfunckt if anyone ever pings you on a similar delta issue. I'll try working on this next week. It's 100% a Supervisor issue...the 404 is from the daemon not the delta server.

**Comment by dfunckt** [comment] 2021-03-23 12:52
> Move device to application B
> Supervisor tries to pull application B images but shows the 404 delta error.

This is where the bug is -- the Supervisor should not attempt to pull a delta between different apps (i.e. after a move), it used to handle this case and do a full image pull instead so maybe that regressed?

**Comment by cywang117** [comment] 2021-04-12 09:52
@20k-ultra Having trouble reproducing this issue. When you say in the above steps to `Preload application A to your SD card`, is this onto an OS image that was downloaded from the dashboard (i.e. is already associated with an application), or an uninitialized OS image that I should configure & initialize via balena-cli?

**Comment by 20k-ultra** [comment] 2021-04-14 03:41
One of the requirements is the Application A contains only some of Application B. 

So, application A would be services ['main'] and application B is ['main', 'frontend', 'backend']. The idea is that main will download successfully but frontend and backend will get the 404 message.

It shouldn't matter if where the OS came from (provisioned from an app or downloaded via cli).

**Comment by cywang117** [comment] 2021-04-14 07:56
@20k-ultra Still unable to reproduce with those exact steps, where I'm moving device from a single-container `main` service to a multi-container app with `main` as one of the services. The user has mentioned upgrading to 2.73 in JF, which I am trying to repro on but unable to. This had led me to believe that this is not an issue that occurs with 2.73 & Supervisor v12.3.5. I believe this to be an issue of delta compatibility with the user's OS version (2.43.0 & Supervisor v10.2.2). Reasons that led to this conclusion:

- We know that OS v<2.47 will not work with balena (v3) deltas.
- In the attached logs of the JF thread, There are log lines indicating that the device is trying to apply v3 balena deltas:
```
Mar 22 16:39:47 8289546 resin-supervisor[7591]: [debug]   delta([proxy-server] registry2.balena-cloud.com/v2/6b63c6fc99200a63b715c1852e1cf879@sha256:9bf64ad0ef6a673c01a5db7762ec9ed16859d38aba90b542ae9032d9fc15a6ab): Starting delta to registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e@sha256:10ff3d53b7618dae981ee40a75787f29d30e463220a6027b2cb927232cb2532c
Mar 22 16:39:48 8289546 resin-supervisor[7591]: [debug]   delta([network-manager] registry2.balena-cloud.com/v2/8771c44d4f1021c186250777718f18e6@sha256:4eae4bdb85b1c4d6bc6d751355bbaaca5d740f7a8b082473783c9b23468b8d59): Starting delta to registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad@sha256:8c235bbf206879513ba486afdfc9573e5d65cfde715fb430f0db6abcd8067949
Mar 22 16:39:48 8289546 resin-supervisor[7591]: [debug]   delta([wma-front-end] registry2.balena-cloud.com/v2/a514c5e0a37006bd0ba45c79d7d1564b@sha256:a4b04d747354dc188f8b1b2e9d5bef86cb0c8cc0cc8f292461e807f314af7435): Starting delta to registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1@sha256:38bd4832bbb77ef732cae0a580e58595f974b2e302be35acaf90e51fe44f0b62
Mar 22 16:39:48 8289546 resin-supervisor[7591]: [debug]   delta([proxy-server] registry2.balena-cloud.com/v2/6b63c6fc99200a63b715c1852e1cf879@sha256:9bf64ad0ef6a673c01a5db7762ec9ed16859d38aba90b542ae9032d9fc15a6ab): Applying balena delta...
Mar 22 16:39:48 8289546 resin-supervisor[7591]: [debug]   delta([proxy-server] registry2.balena-cloud.com/v2/6b63c6fc99200a63b715c1852e1cf879@sha256:9bf64ad0ef6a673c01a5db7762ec9ed16859d38aba90b542ae9032d9fc15a6ab): Using registry auth token
Mar 22 16:39:49 8289546 resin-supervisor[7591]: [debug]   delta([network-manager] registry2.balena-cloud.com/v2/8771c44d4f1021c186250777718f18e6@sha256:4eae4bdb85b1c4d6bc6d751355bbaaca5d740f7a8b082473783c9b23468b8d59): Applying balena delta...
Mar 22 16:39:49 8289546 resin-supervisor[7591]: [debug]   delta([network-manager] registry2.balena-cloud.com/v2/8771c44d4f1021c186250777718f18e6@sha256:4eae4bdb85b1c4d6bc6d751355bbaaca5d740f7a8b082473783c9b23468b8d59): Using registry auth token
Mar 22 16:39:49 8289546 resin-supervisor[7591]: [debug]   delta([wma-front-end] registry2.balena-cloud.com/v2/a514c5e0a37006bd0ba45c79d7d1564b@sha256:a4b04d747354dc188f8b1b2e9d5bef86cb0c8cc0cc8f292461e807f314af7435): Applying balena delta...
Mar 22 16:39:49 8289546 resin-supervisor[7591]: [debug]   delta([wma-front-end] registry2.balena-cloud.com/v2/a514c5e0a37006bd0ba45c79d7d1564b@sha256:a4b04d747354dc188f8b1b2e9d5bef86cb0c8cc0cc8f292461e807f314af7435): Using registry auth token
Mar 22 16:39:51 8289546 resin-supervisor[7591]: [info]    Internet Connectivity: OK
Mar 22 16:39:55 8289546 resin-supervisor[7591]: [debug]   delta([network-manager] registry2.balena-cloud.com/v2/8771c44d4f1021c186250777718f18e6@sha256:4eae4bdb85b1c4d6bc6d751355bbaaca5d740f7a8b082473783c9b23468b8d59): Delta failed with Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3: No such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3
Mar 22 16:39:55 8289546 resin-supervisor[7591]: [event]   Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3: No such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3 ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3: No such image: registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad:delta-a5621a43ace90fd3 \n    at /usr/src/app/dist/app.js:596:111352\n    at /usr/src/app/dist/app.js:596:111315\n    at m.buildPayload (/usr/src/app/dist/app.js:596:111325)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:596:110825)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"image":{"name":"registry2.balena-cloud.com/v2/fa50cc9ddee2dadac5c2ed31244919ad@sha256:8c235bbf206879513ba486afdfc9573e5d65cfde715fb430f0db6abcd8067949","appId":1576282,"serviceId":606500,"serviceName":"network-manager","imageId":3424924,"releaseId":1738659,"dependent":0,"dockerImageId":null}}
Mar 22 16:39:56 8289546 resin-supervisor[7591]: [debug]   delta([proxy-server] registry2.balena-cloud.com/v2/6b63c6fc99200a63b715c1852e1cf879@sha256:9bf64ad0ef6a673c01a5db7762ec9ed16859d38aba90b542ae9032d9fc15a6ab): Delta failed with Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd: No such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd
Mar 22 16:39:56 8289546 resin-supervisor[7591]: [debug]   delta([wma-front-end] registry2.balena-cloud.com/v2/a514c5e0a37006bd0ba45c79d7d1564b@sha256:a4b04d747354dc188f8b1b2e9d5bef86cb0c8cc0cc8f292461e807f314af7435): Delta failed with Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505: No such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505
Mar 22 16:39:56 8289546 resin-supervisor[7591]: [event]   Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd: No such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd: No such image: registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e:delta-6d29fca1b867cefd \n    at /usr/src/app/dist/app.js:596:111352\n    at /usr/src/app/dist/app.js:596:111315\n    at m.buildPayload (/usr/src/app/dist/app.js:596:111325)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:596:110825)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"image":{"name":"registry2.balena-cloud.com/v2/469ed301f1f73144680dfce2305dc69e@sha256:10ff3d53b7618dae981ee40a75787f29d30e463220a6027b2cb927232cb2532c","appId":1576282,"serviceId":606499,"serviceName":"proxy-server","imageId":3424922,"releaseId":1738659,"dependent":0,"dockerImageId":null}}
Mar 22 16:39:56 8289546 resin-supervisor[7591]: [event]   Event: Image download error {"error":{"message":"(HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505: No such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505 ","stack":"Error: (HTTP code 404) no such image - no such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505: No such image: registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1:delta-11ee1c5a4603e505 \n    at /usr/src/app/dist/app.js:596:111352\n    at /usr/src/app/dist/app.js:596:111315\n    at m.buildPayload (/usr/src/app/dist/app.js:596:111325)\n    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:596:110825)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"image":{"name":"registry2.balena-cloud.com/v2/43cacc3a15795c2cf74f2566d331ebe1@sha256:38bd4832bbb77ef732cae0a580e58595f974b2e302be35acaf90e51fe44f0b62","appId":1576282,"serviceId":606501,"serviceName":"wma-front-end","imageId":3424926,"releaseId":1738659,"dependent":0,"dockerImageId":null}}
Mar 22 16:39:58 8289546 resin-supervisor[7591]: [event]   Event: Service started {"service":{"appId":1576282,"serviceId":953102,"serviceName":"select-dtb","releaseId":1738659}}
```

This "Applying balena delta..." log line is suspicious, as "Applying rsync delta..." should have been logged, as the user's OS is <2.47. [Here](https://github.com/balena-os/balena-supervisor/blob/v10.2.2/src/lib/docker-utils.ts#L266) is the reference from Supervisor v10.2.2 which the user is running, which shows a log call with "rsync" if deltas are v2 and a log call with "balena" if v3.

Recommendation: Ask the user to check their delta version via `Diagnostics > Supervisor state`. If *_DELTA_VERSION === 3, that's the cause of these log errors. I don't know why they're on v3 deltas, on an old OS version that can't support v3.

**Comment by dfunckt** [comment] 2021-04-14 08:06
Supervisors until the one included in balenaOS 2.47 try to update via deltas when a device is moved between apps. It does not matter that this fails -- Supervisors should not use deltas after a move and this is a bug that we have fixed. The way forward is for the customer to update their host OS.

**Comment by cywang117** [comment] 2021-04-14 08:15
@dfunckt Thanks for the summary!

@20k-ultra Would you like to ping the user, since you're assigned to the ticket? If not I can.

**Comment by cywang117** [comment] 2021-04-20 04:46
To summarize: 

I haven't been able to consistently reproduce this on v2.43.0 with Supervisor 10.2.2, by preloading, then moving device between applications which share at least one service name. What we do know:

- Supervisor should not be using deltas when moving between applications. I haven't observed deltas being used in OS 2.7x (newer versions). Deltas being used when moving between application can only happen when the device has deltas enabled. 
- Even when a device on OS 2.4x does not have deltas enabled, its delta version may be set to version 3, resulting in the "Applying balena deltas..." log line as seen in the user's issue.

With this in mind, and with the inconsistency of the issue, the recommendation when faced with this issue (which we've observed to happen with older OS+Supervisor versions) is to update the Host OS.

**Closed by cywang117** 2021-04-20 04:46 UTC
