### ISSUE TITLE
New services can be started when an update lock is in place

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#1244] opened 2020-04-01 12:58 UTC
To reproduce, install 
https://github.com/balena-io-playground/balena-updates-lock
and then push 
https://github.com/balenalabs/balena-sound
( I don't think the bug is specific to the latter, but that's what was originally used to hit this).

The service from `balena-updates-lock` will stay running, but some of the services from `balena-sound` will also be started.

Version: 10.8.0

**Comment by 20k-ultra** [comment] 2020-10-21 01:19
Still happening as of latest (v12.0.7)

**Comment by 20k-ultra** [comment] 2020-10-21 01:22
It makes sense that this behavior happens. The container has said leave me alone and when we apply new target state that container is not needed but also cannot be removed so we move on. The only alternative is we block moving to another release because this container has an update lock. 

We either block moving to next update and log "Release migration blocked due to update-lock on {container} service"

OR

Roll out release (currently what's happening and we perceive it as a bug) and add a log to target state apply "{container} service could not be removed due to update-lock but new release has been deployed".

**Comment by cywang117** [comment] 2023-02-16 21:55
Closing as I agree with the latest comment here -- update locks were only intended to keep certain services running while they're performing critical operations. Any other usage is not what was intended, and we should think carefully about extending the original update lock use case to support these other usages.

**Closed by cywang117** 2023-02-16 21:55 UTC
Labels: type/bug, High priority
