### ISSUE TITLE
Blink doesn't work on pi4

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-supervisor#1264] opened 2020-04-13 10:59 UTC

**Comment by cywang117** [comment] 2023-02-16 22:16
Closing; not able to reproduce and not enough info here. If this was an error, please re-open with Supervisor and OS versions, and the output of `balena exec -it balena_supervisor env | grep 'LED_FILE'`.

**Closed by cywang117** 2023-02-16 22:16 UTC

**Comment by cywang117** [comment] 2026-03-12 16:05
Thanks @theashyster , what's the OS version you encountered this on?

**Comment by cywang117** [comment] 2026-03-18 23:49
Thanks @theashyster . Will look into this when I get a chance, feel free to follow this issue for updates, or if so interested, to contribute a fix :)
