### ISSUE TITLE
Images from old release not cleaned up

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-supervisor#1616] opened 2021-03-08 16:43 UTC
A device has 5 releases and all are running fine. After deploying another release with only 2 services now, the other 3 are removed but their images remained on the device. Confirmed in the docker-compose file of the release that the services should be removed which they are but the Images should also be removed...

The Supervisor has some cleanup functionality for images but not sure why it isn't triggering for this device. If you restart the Supervisor you can see applying target state follow by a finished applying target state so the Supervisor thinks there is nothing to clean up. (This is where the cleanup code exists)

https://github.com/balena-io/balena-supervisor/blob/dc96cca5e5fddc277d5a466bcd17654ccce67995/src/compose/application-manager.ts#L210-L212

**Comment by 20k-ultra** [comment] 2021-03-08 18:08
The issue with this instance was that docker images were cleaned up but the database still have entries for these images. We should audit the image cleanup to also cleanup the database entries.

**Comment by 20k-ultra** [comment] 2021-03-08 18:38
Figuring out how to remove the image table from the database file would also solve this however another issue will be created if we go that route.

**Comment by 20k-ultra** [comment] 2021-03-11 19:56
Can we remove entries to images from other applications ? I found that image records from another application were causing the Supervisor to behave weird.

**Comment by pipex** [comment] 2021-03-12 22:11
Here are some steps to replicate one border case that caused this by Andrea

> Steps to replicate the problem:
> BUILD AND DEPLOY THE SAME IMAGE IN TWO DIFFERENT APPS:
> 1) balena-staging build (in my case it was for rpi4)
> 2) balena-staging deploy support_test balena-console-logs_main (application with one device)
> 3) balena-staging deploy support_test_2 balena-console-logs_main (application without deivces)
> 
> MOVE THE DEVICE
> 1) go to the dashboard and move the device from one application to another.
> 
> OS: balenaOS 2.67.3+rev4
> Supervisor: 12.3.0

**Comment by cywang117** [comment] 2021-03-17 10:23
Here is a possible way to easily reproduce the issue:

1. `balena push` [node-hello-world](https://github.com/balena-io-examples/balena-node-hello-world)
2. `balena push` [python-hello-world](https://github.com/balena-io-examples/balena-python-hello-world)
3. `balena images -a`, notice that the node image from the first push is still there.

Upon checking the image table in the DB following step 3, the only image listed there is the python service image.

Verifying now & will edit post with results.

**Comment by 20k-ultra** [comment] 2021-05-31 19:14
@cywang117 those steps don't reproduce a device with image data from previous releases. It just shows you how to get the error when the bug is present I believe. I'm saying this because this images from old release has only been a nuisance until we found people deleting releases which happened to have image metadata stuck on the device and that caused issues with reporting the current state. The source of how the device still has images in the database is unknown.

**Comment by cywang117** [comment] 2021-06-02 16:52
This issue seems to be reaching critical mass, and causing quite a bit of friction on support recently :|

**Comment by cywang117** [comment] 2021-06-16 10:15
The issue title can have two meanings now that I'm thinking about it:
- The images table of the Supervisor database isn't cleaning up old release entries
- Physical images that are Supervisor-related aren't being cleaned up

In the case of the second bullet point, it appears that old Supervisor base images still remain after HUP, when the expected behavior is that they'd be removed (cc @floion). My question is, is the Supervisor expected to cleanup host or Supervisor related images that are outdated? Is it expected to clean up user-pulled images? (I'm assuming the answer to this 2nd question is no.)

**Comment by pipex** [comment] 2021-06-16 14:49
Good point about the title  @cywang117, I think from the top description it was supposed to mean the second one, but given the linked tickets is safe to say it means both.

Regarding old supervisor images after HUP, I don't think it falls within the scope of this issue. Since the supervisor does not not perform its own update. There is some code to remove old supervisor images but since moving to our registry I think it broke https://github.com/balena-os/balena-supervisor/blob/master/src/compose/images.ts#L397-L406

Regarding your questions 

I think this is a nice bonus, but there may be no way to do it since supervisor images are indistinguishable from other images
> Is the Supervisor expected to cleanup host or Supervisor related images that are outdated?

The expectation for users is that the supervisor maintains user-pulled images (that's why local mode takes a snapshot to clean images)
> Is it expected to clean up user-pulled images?

**Comment by 20k-ultra** [comment] 2021-08-03 15:56
@pipex I recall that you mentioned running 12.9.6 which contains https://github.com/balena-os/balena-supervisor/pull/1749 and it resolved a device. We should be able to close this then right or did you not make the PR automatically close it to do some more testing ?

**Comment by pipex** [comment] 2021-08-03 15:58
That device has reverted now. I didn't want to make this close automatically so people wouldn't be bombarded with reopened tickets on support. Closing now

**Closed** 2021-09-28 01:38 UTC
