### ISSUE TITLE
Several machines stuck upgrading to 14.9.7

### ISSUE THREAD

**Issue by wojciechczyz** [balena-os/balena-supervisor#2148] opened 2023-03-25 10:20 UTC
I got 4 machines that were trying to upgrade to 14.9.7, likely at the same time trying to upgrade OS.
All are stuck after restart, diagnostic shows that supervisor may be unhealthy

**Comment by wojciechczyz** [comment] 2023-03-25 12:17
I suspect they may have been on Raspberry Pi 2, and deployed since years with Raspberry pi 3 image. Did we added something that is now explicitely failing on RPi 2 with image of RPi 3?

**Comment by cywang117** [comment] 2023-03-27 08:08
@wojciechczyz , We merged a change with 14.9.6 to use multi-arch builds for the Supervisor, which resulted in a cached build using the wrong architecture between arm architectures in 14.9.7. We reverted the change in 14.9.8 as there are some cases which the change didn't handle in https://github.com/balena-os/balena-supervisor/pull/2147. Could you try upgrading to 14.9.8 and see if the issue is resolved?

**Comment by pipex** [comment] 2023-04-25 18:51
This should be fixed as of 14.9.8

**Closed by pipex** 2023-04-25 18:51 UTC
